BEGIN;

CREATE TABLE IF NOT EXISTS files (
  id BIGSERIAL PRIMARY KEY,
  path TEXT UNIQUE NOT NULL,
  sha256 CHAR(64) UNIQUE NOT NULL,
  hdu_index INT,
  ingested_at TIMESTAMPTZ DEFAULT NOW(),
  hdr_small JSONB
);

CREATE TABLE IF NOT EXISTS flags (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS file_flags (
  file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  flag_id INT NOT NULL REFERENCES flags(id) ON DELETE CASCADE,
  value BOOLEAN NOT NULL,
  info JSONB,
  PRIMARY KEY (file_id, flag_id)
);

CREATE TABLE IF NOT EXISTS runs (
  id BIGSERIAL PRIMARY KEY,
  file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
  outdir TEXT NOT NULL,
  run_name TEXT NOT NULL,
  dest_dirs JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMIT;
